### Get all users

GET http://localhost:3000/api/users HTTP/1.1


### GET a single user
GET http://localhost:3000/api/users/Leon HTTP/1.1

### GET a single user which doesn't exist
GET http://localhost:3000/api/users/peter HTTP/1.1

### Delete a user
DELETE http://localhost:3000/api/users/Leon HTTP/1.1